In [30]:
import pandas as pd

In [31]:
pd.__version__

'3.0.6'

In [32]:
df = pd.read_csv('data.csv')

In [33]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [34]:
len(df)

10000

In [35]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [36]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [37]:
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [38]:
df['horsepower'].median()

np.float64(254.0)

In [39]:
df['horsepower'].mode()[0]

np.float64(252.0)

In [40]:
df['horsepower'].fillna(252).median()

np.float64(252.0)

In [57]:
X = df[df['origin'] == 'Asia'][['model_year', 'vehicle_weight']].iloc[:7]

In [58]:
X

    model_year  vehicle_weight
2         1996            4240
6         1992            4310
8         1997            4230
10        1978            4420
15        2007            3950
16        2021            4750
22        2019            4450

In [59]:
X = X.to_numpy()

In [60]:
X

array([[1996, 4240],
       [1992, 4310],
       [1997, 4230],
       [1978, 4420],
       [2007, 3950],
       [2021, 4750],
       [2019, 4450]])

In [61]:
XT=X.T

In [62]:
XT

array([[1996, 1992, 1997, 1978, 2007, 2021, 2019],
       [4240, 4310, 4230, 4420, 3950, 4750, 4450]])

In [68]:
XTX= XT @ X

In [69]:
XTX

array([[ 28041424,  60750580],
       [ 60750580, 131950500]])

In [70]:
import numpy as np
inv = np.linalg.inv(XTX)

In [71]:
inv

array([[ 1.39675281e-05, -6.43071025e-06],
       [-6.43071025e-06,  2.96830537e-06]])

In [72]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [74]:
w = inv @ X.T @ y

In [75]:
w

array([0.2327492 , 0.13644777])

In [76]:
print(np.sum(w))

0.3691969690492686